# Generated by Django 5.2.7 on 2026-09-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('provider_type', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('district', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('6 Months', '6 Months'), ('1 Year', '1 Year'), ('3 Years', '3 Years'), ('5 Years', '5 Years')], max_length=20)),
                ('date', models.DateField()),
                ('employment_status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrack.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uan_demo', models.CharField(blank=True, max_length=30)),
                ('employer_name', models.CharField(blank=True, max_length=150)),
                ('job_role', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('employment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Employed', 'Employed'), ('Seeking', 'Seeking'), ('Unemployed', 'Unemployed')], max_length=20)),
                ('trainee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skilltrack.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Training', 'Training'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrack.course')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrack.provider')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilltrack.trainee')),
            ],
        ),
    ]
