# Generated by Django 5.2.7 on 2026-09-04 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0002_trainee_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Authority', 'Authority'), ('Trainer', 'Trainer'), ('Trainee', 'Trainee')], max_length=20)),
                ('trainee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skilltrack.trainee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
