# Generated by Django 5.2.7 on 2026-09-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0004_trainingbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=150)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('registration_date', models.DateField()),
            ],
        ),
    ]
