# Generated by Django 5.2.7 on 2026-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0006_trainerregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
