# Generated by Django 5.2.7 on 2026-09-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0007_provider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatch',
            name='attendance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainingbatch',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
