# Generated by Django 5.2.7 on 2026-09-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0008_trainingbatch_attendance_trainingbatch_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatch',
            name='remarks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
