# Generated by Django 5.2.7 on 2026-09-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0009_trainingbatch_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingbatch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
