# Generated by Django 5.2.7 on 2026-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0011_notification_alter_followup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
