# Generated by Django 5.2.7 on 2026-09-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0012_followup_email_sent_followup_email_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Training', 'Training'), ('Completed', 'Completed'), ('Dropped', 'Dropped')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='skilltrack.trainingbatch')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='skilltrack.trainee')),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(fields=('trainee', 'batch'), name='unique_trainee_batch_request')],
            },
        ),
    ]
