# Generated by Django 6.0.3 on 2026-09-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0013_alter_training_status_trainingregistrationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Seeking', 'Seeking'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed')], default='Seeking', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Seeking', 'Seeking'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-Employed')], default='Seeking', max_length=50),
        ),
    ]
