# Generated by Django 6.0.3 on 2026-09-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0014_alter_employment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UANVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uan', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('verification_message', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(auto_now=True)),
                ('employment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uan_verifications', to='skilltrack.employment')),
            ],
        ),
    ]
