# Generated by Django 6.0.3 on 2026-09-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0015_uanverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfEmploymentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('work_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verification_message', models.CharField(blank=True, max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('employment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_employment_verification', to='skilltrack.employment')),
            ],
        ),
    ]
