# Generated by Django 6.0.3 on 2026-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0016_selfemploymentverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employment',
            name='business_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employment',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employment',
            name='work_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
