# Generated by Django 6.0.3 on 2026-09-08 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0017_employment_business_name_employment_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveIntegerField(default=0)),
                ('attended_classes', models.PositiveIntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0)),
                ('total_assignments', models.PositiveIntegerField(default=0)),
                ('completed_assignments', models.PositiveIntegerField(default=0)),
                ('assignment_score', models.FloatField(default=0)),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('completed_assessments', models.PositiveIntegerField(default=0)),
                ('assessment_score', models.FloatField(default=0)),
                ('practical_score', models.FloatField(default=0)),
                ('progress_percentage', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('trainer_remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='skilltrack.trainee')),
                ('training', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='skilltrack.training')),
            ],
        ),
    ]
