# Generated by Django 6.0.3 on 2026-09-10 17:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0019_trainee_consent_given_trainee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skills_taught',
            field=models.TextField(blank=True, help_text='Comma-separated skills taught by this course.'),
        ),
        migrations.AddField(
            model_name='employment',
            name='apprenticeship_converted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='apprenticeship_expected_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employment',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employment',
            name='recorded_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employment',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employment',
            name='stipend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employment',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_outcomes', to='skilltrack.training'),
        ),
        migrations.AddField(
            model_name='employment',
            name='verification_status',
            field=models.CharField(choices=[('Not Verified', 'Not Verified'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Not Verified', max_length=20),
        ),
        migrations.AddField(
            model_name='employment',
            name='wage_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Daily', 'Daily'), ('Annual', 'Annual')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to='skilltrack.trainingbatch'),
        ),
        migrations.AddField(
            model_name='training',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='training',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employment',
            name='status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-employed'), ('Apprenticeship', 'Apprenticeship'), ('Further Training', 'Further training'), ('Other', 'Other'), ('Seeking', 'Seeking work')], default='Seeking', max_length=20),
        ),
        migrations.AlterField(
            model_name='employment',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_records', to='skilltrack.trainee'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='employment_status',
            field=models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self-Employed', 'Self-employed'), ('Apprenticeship', 'Apprenticeship'), ('Further Training', 'Further training'), ('Other', 'Other'), ('Seeking', 'Seeking work')], default='Seeking', max_length=50),
        ),
        migrations.CreateModel(
            name='OccupationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('occupation', 'skill'), name='unique_occupation_skill')],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_on', models.DateField()),
                ('still_employed', models.BooleanField()),
                ('same_employer', models.BooleanField(blank=True, null=True)),
                ('changed_occupation', models.BooleanField(blank=True, null=True)),
                ('reason_for_leaving', models.CharField(blank=True, choices=[('', '---------'), ('Low salary', 'Low salary'), ('Relocation', 'Relocation'), ('Poor working conditions', 'Poor working conditions'), ('Skill mismatch', 'Skill mismatch'), ('Better opportunity', 'Better opportunity'), ('Personal/family reason', 'Personal/family reason'), ('Lack of growth', 'Lack of growth'), ('Employer issue', 'Employer issue'), ('Other', 'Other')], max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_records', to='skilltrack.employment')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_records', to='skilltrack.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRelevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('skills_used', models.TextField(blank=True)),
                ('skills_not_used', models.TextField(blank=True)),
                ('missing_skills', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_feedback', to='skilltrack.trainee')),
                ('training', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relevance_feedback', to='skilltrack.training')),
            ],
        ),
        migrations.CreateModel(
            name='WageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('frequency', models.CharField(default='Monthly', max_length=20)),
                ('recorded_on', models.DateField()),
                ('source', models.CharField(default='Outcome', max_length=30)),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_records', to='skilltrack.employment')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wage_records', to='skilltrack.trainee')),
            ],
            options={
                'ordering': ['recorded_on', 'id'],
            },
        ),
    ]
