# Generated by Django 6.0.3 on 2026-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0020_course_skills_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employment_proof',
            field=models.FileField(blank=True, null=True, upload_to='employment_proofs/'),
        ),
        migrations.AddField(
            model_name='employment',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('UAN', 'UAN'), ('Employment Proof', 'Employment Proof'), ('Manual', 'Manual Verification')], max_length=30),
        ),
    ]
