# Generated by Django 6.0.3 on 2026-09-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0021_employment_employment_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='employment_proof_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
