# Generated by Django 6.0.3 on 2026-09-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack', '0022_employment_employment_proof_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='uan_verified_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
